### ISSUE TITLE
header hidden after reload

### ISSUE THREAD

**Issue by lolaswift** [samarthagarwal/ScrollingHeader#2]
Hey Smarath, you directive is the simpliest I could found and it works. However, I ran into a small bug maybe you can give me a hand? 
I have a list of item -> I scroll down->header become hidden. This works perfectly. However, while the header bar is still hidden, I trigger a reload of the data. After the reload finished, the header remains hidden.

**Comment by lolaswift** [comment]
update: the issue only happens on android and desktop browser.

**Comment by samarthagarwal** [comment]
Can you share a working demo (on StackBlitz)?

**Comment by lolaswift** [comment]
@samarthagarwal 
Sorry for my late reply.
https://stackblitz.com/edit/ionic3-header
if you scroll down until the header's hidden, click on a card, you'll see the result.

**Comment by samarthagarwal** [comment]
I added a fix to your code [here](https://stackblitz.com/edit/ionic3-header-rymahe).

**Comment by lolaswift** [comment]
@samarthagarwal I tried the same but in a wrong order and it didn't work. That's the big difference between a noob and an expert. You've fixed my issue and thank you so much for the quick response as well. You solution is the simplest I've found on the Internet and it works! I'd like to buy you a beer sir. Do you have a donation button or?

**Comment by samarthagarwal** [comment]
Glad I could help. I do not have a donate button but feel free to check out [my courses on Udemy](https://www.udemy.com/user/samarthagarwal5/).

**Comment by lolaswift** [comment]
Hi Samarth,
I just purchased your ionic&firebase course. Thanks again!
Regards,
Lola
